# Builds docker images used by engine-build.yml
name: Docker Images Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docker-build-v2/amd64-linux/**'
      - 'docker-build-v2/amd64-windows/**'
  pull_request:
    paths:
      - 'docker-build-v2/amd64-linux/**'
      - 'docker-build-v2/amd64-windows/**'
jobs:
  build-images:
    if: github.repository == 'beyond-all-reason/spring' || github.event_name == 'workflow_dispatch'
    name: Build ${{ matrix.system }} docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system:
          - amd64-linux
          - amd64-windows
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker-build-v2/${{ matrix.system }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/recoil-build-${{ matrix.system }}:latest
